TILESIZE = 100

LVL1_ROWS = 4
LVL1_COLS = 4

LVL2_ROWS = 6
LVL2_COLS = 6

SCREEN_SIZE_LVL1 = (TILESIZE*LVL1_ROWS,TILESIZE*LVL1_COLS+TILESIZE)
SCREEN_SIZE_LVL2 = (TILESIZE*LVL2_ROWS,TILESIZE*LVL2_COLS+TILESIZE)

#MENU_SCREEN_SIZE = (TILESIZE*9,TILESIZE*9+TILESIZE)

